# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.8.dev0+g9195f63.d20221202'
__version_tuple__ = version_tuple = (0, 0, 8, 'dev0', 'g9195f63.d20221202')
