internal_project_section_mapping = [
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'PROJECT_TITLE',    'internal_field_key': 'title'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'PROJECT_TYPE',     'internal_field_key': ''},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'PROJECT_SUMMARY',  'internal_field_key': 'description'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'INSTITUTE',        'internal_field_key': 'institution'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'DEPARTMENT',       'internal_field_key': 'department'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'LABORATORY',       'internal_field_key': ''},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'LAST_NAME',        'internal_field_key': 'PI_last_name'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'FIRST_NAME',       'internal_field_key': 'PI_first_name'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'ADDRESS',          'internal_field_key': 'address'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'EMAIL',            'internal_field_key': 'PI_email'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'PHONE',            'internal_field_key': 'phone'},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'FUNDING_SOURCE',   'internal_field_key': ''},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'PROJECT_COMMENTS', 'internal_field_key': ''},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'PUBLICATIONS',     'internal_field_key': ''},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'CONTRIBUTORS',     'internal_field_key': ''},
    {'mwtab_section_key': 'PROJECT', 'internal_section_key': 'project', 'mwtab_field_key': 'DOI',              'internal_field_key': ''}
]


internal_study_section_mapping = [
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_TITLE',    'internal_field_key': 'title'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_TYPE',     'internal_field_key': 'type'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_SUMMARY',  'internal_field_key': 'description'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'INSTITUTE',      'internal_field_key': 'institution'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'DEPARTMENT',     'internal_field_key': 'department'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'LABORATORY',     'internal_field_key': ''},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'LAST_NAME',      'internal_field_key': 'contact_last_name'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'FIRST_NAME',     'internal_field_key': 'contact_first_name'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'ADDRESS',        'internal_field_key': 'address'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'EMAIL',          'internal_field_key': 'contact_email'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'PHONE',          'internal_field_key': 'phone'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'NUM_GROUPS',     'internal_field_key': ''},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'TOTAL_SUBJECTS', 'internal_field_key': ''},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'NUM_MALES',      'internal_field_key': ''},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'NUM_FEMALES',    'internal_field_key': ''},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_COMMENTS', 'internal_field_key': 'comments'},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'PUBLICATIONS',   'internal_field_key': ''},
    {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'SUBMIT_DATE',    'internal_field_key': ''}
]


# internal_study_section_mapping = [
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_TITLE',    'internal_field_key': 'title'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_TYPE',     'internal_field_key': 'type'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_SUMMARY',  'internal_field_key': 'description'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'INSTITUTE',      'internal_field_key': 'institution'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'DEPARTMENT',     'internal_field_key': 'department'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'LABORATORY',     'internal_field_key': ''},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'LAST_NAME',      'internal_field_key': 'PI_last_name'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'FIRST_NAME',     'internal_field_key': 'PI_first_name'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'ADDRESS',        'internal_field_key': 'address'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'EMAIL',          'internal_field_key': 'PI_email'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'PHONE',          'internal_field_key': 'phone'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'NUM_GROUPS',     'internal_field_key': ''},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'TOTAL_SUBJECTS', 'internal_field_key': ''},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'NUM_MALES',      'internal_field_key': ''},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'NUM_FEMALES',    'internal_field_key': ''},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'STUDY_COMMENTS', 'internal_field_key': 'comments'},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'PUBLICATIONS',   'internal_field_key': ''},
#     {'mwtab_section_key': 'STUDY', 'internal_section_key': 'study', 'mwtab_field_key': 'SUBMIT_DATE',    'internal_field_key': ''}
# ]


internal_subject_section_mapping = [
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'SUBJECT_TYPE',               'internal_field_key': 'species_type'},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'SUBJECT_SPECIES',            'internal_field_key': 'species'},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'TAXONOMY_ID',                'internal_field_key': 'taxonomy_id'},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'GENOTYPE_STRAIN',            'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'AGE_OR_AGE_RANGE',           'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'WEIGHT_OR_WEIGHT_RANGE',     'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HEIGHT_OR_HEIGHT_RANGE',     'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'GENDER',                     'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_RACE',                 'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_ETHNICITY',            'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_TRIAL_TYPE',           'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_LIFESTYLE_FACTORS',    'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_MEDICATIONS',          'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_PRESCRIPTION_OTC',     'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_SMOKING_STATUS',       'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_ALCOHOL_DRUG_USE',     'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_NUTRITION',            'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_INCLUSION_CRITERIA',   'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'HUMAN_EXCLUSION_CRITERIA',   'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'ANIMAL_ANIMAL_SUPPLIER',     'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'ANIMAL_HOUSING',             'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'ANIMAL_LIGHT_CYCLE',         'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'ANIMAL_FEED',                'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'ANIMAL_WATER',               'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'ANIMAL_INCLUSION_CRITERIA',  'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'CELL_BIOSOURCE_OR_SUPPLIER', 'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'CELL_STRAIN_DETAILS',        'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'SUBJECT_COMMENTS',           'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'CELL_PRIMARY_IMMORTALIZED',  'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'CELL_PASSAGE_NUMBER',        'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'CELL_COUNTS',                'internal_field_key': ''},
    {'mwtab_section_key': 'SUBJECT', 'internal_section_key': 'subject', 'mwtab_field_key': 'SPECIES_GROUP',              'internal_field_key': ''}
]


internal_collection_section_mapping = [
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_SUMMARY',           'internal_field_key': 'description'},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_PROTOCOL_ID',       'internal_field_key': 'id'},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_PROTOCOL_FILENAME', 'internal_field_key': 'filename'},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_PROTOCOL_COMMENTS', 'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'SAMPLE_TYPE',                  'internal_field_key': 'sample_type'},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_METHOD',            'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_LOCATION',          'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_FREQUENCY',         'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_DURATION',          'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_TIME',              'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'VOLUMEORAMOUNT_COLLECTED',     'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'STORAGE_CONDITIONS',           'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_VIALS',             'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'STORAGE_VIALS',                'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'COLLECTION_TUBE_TEMP',         'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'ADDITIVES',                    'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'BLOOD_SERUM_OR_PLASMA',        'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'TISSUE_CELL_IDENTIFICATION',   'internal_field_key': ''},
    {'mwtab_section_key': 'COLLECTION', 'internal_section_key': 'protocol', 'internal_type': 'collection', 'mwtab_field_key': 'TISSUE_CELL_QUANTITY_TAKEN',   'internal_field_key': ''}
]


internal_treatment_section_mapping = [
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_SUMMARY',           'internal_field_key': 'description'},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_PROTOCOL_ID',       'internal_field_key': 'id'},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_PROTOCOL_FILENAME', 'internal_field_key': 'filename'},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_PROTOCOL_COMMENTS', 'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT',                  'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_COMPOUND',            'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_ROUTE',          'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_DOSE',         'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_DOSEVOLUME',          'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_DOSEDURATION',              'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'TREATMENT_VEHICLE',     'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_VET_TREATMENTS',           'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_ANESTHESIA',             'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_ACCLIMATION_DURATION',                'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_FASTING',         'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_ENDP_EUTHANASIA',                    'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_ENDP_TISSUE_COLL_LIST',        'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_ENDP_TISSUE_PROC_METHOD',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'ANIMAL_ENDP_CLINICAL_SIGNS',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'HUMAN_FASTING',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'HUMAN_ENDP_CLINICAL_SIGNS',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_STORAGE',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_GROWTH_CONTAINER',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_GROWTH_CONFIG',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_GROWTH_RATE',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_INOC_PROC',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_MEDIA',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_ENVIR_COND',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_HARVESTING',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_GROWTH_SUPPORT',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_GROWTH_LOCATION',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_PLOT_DESIGN',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_LIGHT_PERIOD',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_HUMIDITY',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_TEMP',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_WATERING_REGIME',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_NUTRITIONAL_REGIME',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_ESTAB_DATE',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_HARVEST_DATE',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_GROWTH_STAGE',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_METAB_QUENCH_METHOD',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_HARVEST_METHOD',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'PLANT_STORAGE',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_PCT_CONFLUENCE',   'internal_field_key': ''},
    {'mwtab_section_key': 'TREATMENT', 'internal_section_key': 'protocol', 'internal_type': 'treatment', 'mwtab_field_key': 'CELL_MEDIA_LASTCHANGED',   'internal_field_key': ''}
]


internal_sampleprep_section_mapping = [
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SAMPLEPREP_SUMMARY',             'internal_field_key': 'description'},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SAMPLEPREP_PROTOCOL_ID',         'internal_field_key': 'id'},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SAMPLEPREP_PROTOCOL_FILENAME',   'internal_field_key': 'filename'},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SAMPLEPREP_PROTOCOL_COMMENTS',   'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'PROCESSING_METHOD',              'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'PROCESSING_STORAGE_CONDITIONS',  'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'EXTRACTION_METHOD',              'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'EXTRACT_CONCENTRATION_DILUTION', 'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'EXTRACT_ENRICHMENT',             'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'EXTRACT_CLEANUP',                'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'EXTRACT_STORAGE',                'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SAMPLE_RESUSPENSION',            'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SAMPLE_DERIVATIZATION',          'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SAMPLE_SPIKING',                 'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'ORGAN',                          'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'ORGAN_SPECIFICATION',            'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'CELL_TYPE',                      'internal_field_key': ''},
    {'mwtab_section_key': 'SAMPLEPREP', 'internal_section_key': 'protocol', 'internal_type': 'sample_prep', 'mwtab_field_key': 'SUBCELLULAR_LOCATION',           'internal_field_key': ''}
]


internal_chromatography_section_mapping = [
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CHROMATOGRAPHY_SUMMARY',    'internal_field_key': 'chromatography_description'},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CHROMATOGRAPHY_TYPE',       'internal_field_key': 'chromatography_type'},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'INSTRUMENT_NAME',           'internal_field_key': 'chromatography_instrument_name'},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'COLUMN_NAME',               'internal_field_key': 'column_name'},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'FLOW_GRADIENT',             'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'FLOW_RATE',                 'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'COLUMN_TEMPERATURE',        'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'METHODS_FILENAME',          'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SOLVENT_A',                 'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SOLVENT_B',                 'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'METHODS_ID',                'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'COLUMN_PRESSURE',           'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'INJECTION_TEMPERATURE',     'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'INTERNAL_STANDARD',         'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'INTERNAL_STANDARD_MT',      'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'RETENTION_INDEX',           'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'RETENTION_TIME',            'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SAMPLE_INJECTION',          'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SAMPLING_CONE',             'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'ANALYTICAL_TIME',           'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CAPILLARY_VOLTAGE',         'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'MIGRATION_TIME',            'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'OVEN_TEMPERATURE',          'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'PRECONDITIONING',           'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'RUNNING_BUFFER',            'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'RUNNING_VOLTAGE',           'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SHEATH_LIQUID',             'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'TIME_PROGRAM',              'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'TRANSFERLINE_TEMPERATURE',  'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'WASHING_BUFFER',            'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'WEAK_WASH_SOLVENT_NAME',    'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'WEAK_WASH_VOLUME',          'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'STRONG_WASH_SOLVENT_NAME',  'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'STRONG_WASH_VOLUME',        'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'TARGET_SAMPLE_TEMPERATURE', 'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SAMPLE_LOOP_SIZE',          'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SAMPLE_SYRINGE_SIZE',       'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'RANDOMIZATION_ORDER',       'internal_field_key': ''},
    {'mwtab_section_key': 'CHROMATOGRAPHY', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CHROMATOGRAPHY_COMMENTS',   'internal_field_key': ''}
]


internal_analysys_section_mapping = [
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': 'protocol', 'mwtab_field_key': 'ANALYSIS_TYPE',               'internal_field_key': 'type'},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'NUM_FACTORS',                 'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'ACQUISITION_TIME',            'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'PROCESSING_PARAMETERS_FILE',  'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'ANALYSIS_DISPLAY',            'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'ANALYSIS_COMMENTS',           'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'LABORATORY_NAME',             'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'DETECTOR_TYPE',               'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'SOFTWARE_VERSION',            'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'OPERATOR_NAME',               'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'INSTRUMENT_NAME',             'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'ACQUISITION_DATE',            'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'DATA_FORMAT',                 'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'NUM_METABOLITES',             'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'ACQUISITION_ID',              'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'RAW_FILE',                    'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'PROCESSED_FILE',              'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'INSTRUMENT_PARAMETERS_FILE',  'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'ACQUISITION_PARAMETERS_FILE', 'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'ANALYSIS_PROTOCOL_FILE',      'internal_field_key': ''},
    {'mwtab_section_key': 'ANALYSIS', 'internal_section_key': '',         'mwtab_field_key': 'RANDOMIZATION_ORDER',         'internal_field_key': ''}
]


internal_ms_section_mapping = [
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'INSTRUMENT_NAME',                 'internal_field_key': 'instrument'},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'INSTRUMENT_TYPE',                 'internal_field_key': 'instrument_type'},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'MS_TYPE',                         'internal_field_key': 'ionization'},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'ION_MODE',                        'internal_field_key': 'ion_mode'},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'MS_COMMENTS',                     'internal_field_key': 'description'},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CAPILLARY_TEMPERATURE',           'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CAPILLARY_VOLTAGE',               'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'COLLISION_ENERGY',                'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'COLLISION_GAS',                   'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'DRY_GAS_FLOW',                    'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'DRY_GAS_TEMP',                    'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'FRAGMENT_VOLTAGE',                'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'FRAGMENTATION_METHOD',            'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'GAS_PRESSURE',                    'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'HELIUM_FLOW',                     'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'ION_SOURCE_TEMPERATURE',          'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'ION_SPRAY_VOLTAGE',               'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'IONIZATION',                      'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'IONIZATION_ENERGY',               'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'IONIZATION_POTENTIAL',            'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'MASS_ACCURACY',                   'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'PRECURSOR_TYPE',                  'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'REAGENT_GAS',                     'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SOURCE_TEMPERATURE',              'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SPRAY_VOLTAGE',                   'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'ACTIVATION_PARAMETER',            'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'ACTIVATION_TIME',                 'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'ATOM_GUN_CURRENT',                'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'AUTOMATIC_GAIN_CONTROL',          'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'BOMBARDMENT',                     'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CDL_SIDE_OCTOPOLES_BIAS_VOLTAGE', 'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'CDL_TEMPERATURE',                 'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'DATAFORMAT',                      'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'DESOLVATION_GAS_FLOW',            'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'DESOLVATION_TEMPERATURE',         'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'INTERFACE_VOLTAGE',               'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'IT_SIDE_OCTOPOLES_BIAS_VOLTAGE',  'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'LASER',                           'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'MATRIX',                          'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'NEBULIZER',                       'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'OCTPOLE_VOLTAGE',                 'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'PROBE_TIP',                       'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'RESOLUTION_SETTING',              'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SAMPLE_DRIPPING',                 'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SCAN_RANGE_MOVERZ',               'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SCANNING',                        'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SCANNING_CYCLE',                  'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SCANNING_RANGE',                  'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'SKIMMER_VOLTAGE',                 'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'TUBE_LENS_VOLTAGE',               'internal_field_key': ''},
    {'mwtab_section_key': 'MS', 'internal_section_key': 'protocol', 'internal_type': 'MS', 'mwtab_field_key': 'MS_RESULTS_FILE',                 'internal_field_key': ''}
]


internal_nmr_section_mapping = [
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'INSTRUMENT_NAME',                  'internal_field_key': 'instrument'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'INSTRUMENT_TYPE',                  'internal_field_key': 'instrument_type'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'NMR_EXPERIMENT_TYPE',              'internal_field_key': 'NMR_experiment_type'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'NMR_COMMENTS',                     'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'FIELD_FREQUENCY_LOCK',             'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'STANDARD_CONCENTRATION',           'internal_field_key': 'standard_concentration', 'units': 'standard_concentration%units'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'SPECTROMETER_FREQUENCY',           'internal_field_key': 'spectrometer_frequency', 'units': 'spectrometer_frequency%units'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'NMR_PROBE',                        'internal_field_key': 'NMR_probe'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'NMR_SOLVENT',                      'internal_field_key': 'NMR_solvent'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'NMR_TUBE_SIZE',                    'internal_field_key': 'NMR_tube_size', 'units': 'NMR_tube_size%units'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'SHIMMING_METHOD',                  'internal_field_key': 'shimming_method'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'PULSE_SEQUENCE',                   'internal_field_key': 'pulse_sequence'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'WATER_SUPPRESSION',                'internal_field_key': 'water_suppression'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'PULSE_WIDTH',                      'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'POWER_LEVEL',                      'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'RECEIVER_GAIN',                    'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'OFFSET_FREQUENCY',                 'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'PRESATURATION_POWER_LEVEL',        'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'CHEMICAL_SHIFT_REF_CPD',           'internal_field_key': 'chemical_shift_ref_cpd'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'TEMPERATURE',                      'internal_field_key': 'temperature', 'units': 'temperature%units'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'NUMBER_OF_SCANS',                  'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'DUMMY_SCANS',                      'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'ACQUISITION_TIME',                 'internal_field_key': 'acquisition_time', 'units': 'acquisition_time%units'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'RELAXATION_DELAY',                 'internal_field_key': 'relaxation_delay', 'units': 'relaxation_delay%units'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'SPECTRAL_WIDTH',                   'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'NUM_DATA_POINTS_ACQUIRED',         'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'REAL_DATA_POINTS',                 'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'LINE_BROADENING',                  'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'ZERO_FILLING',                     'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'APODIZATION',                      'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'BASELINE_CORRECTION_METHOD',       'internal_field_key': 'baseline_correction_method'},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'CHEMICAL_SHIFT_REF_STD',           'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'BINNED_INCREMENT',                 'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'BINNED_DATA_NORMALIZATION_METHOD', 'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'BINNED_DATA_PROTOCOL_FILE',        'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'BINNED_DATA_CHEMICAL_SHIFT_RANGE', 'internal_field_key': ''},
    {'mwtab_section_key': 'NMR', 'internal_section_key': 'protocol', 'internal_type': 'NMR', 'mwtab_field_key': 'BINNED_DATA_EXCLUDED_RANGE',       'internal_field_key': ''}
]

